//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.Ux {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class File {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal File() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.Ux.File", typeof(File).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application .
        /// </summary>
        public static string APP_CODE {
            get {
                return ResourceManager.GetString("APP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version.
        /// </summary>
        public static string APP_VERSION {
            get {
                return ResourceManager.GetString("APP_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเลขใบรับรองอิเล็กทรอนิกส์.
        /// </summary>
        public static string CERTIFICATE_NUMBER {
            get {
                return ResourceManager.GetString("CERTIFICATE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่ผู้รับข้อมูล.
        /// </summary>
        public static string COM_ADDR1_T {
            get {
                return ResourceManager.GetString("COM_ADDR1_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน/เวลาที่ Upload .
        /// </summary>
        public static string CREATE_DT {
            get {
                return ResourceManager.GetString("CREATE_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Format Version.
        /// </summary>
        public static string DATA_FORMAT {
            get {
                return ResourceManager.GetString("DATA_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภทข้อมูล.
        /// </summary>
        public static string DOCUMENT_TYPE_NAME_TH {
            get {
                return ResourceManager.GetString("DOCUMENT_TYPE_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่แก้ไขไฟล์ ล่าสุด.
        /// </summary>
        public static string FILE_DATE {
            get {
                return ResourceManager.GetString("FILE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบไฟล์.
        /// </summary>
        public static string FILE_EXTENSION {
            get {
                return ResourceManager.GetString("FILE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อไฟล์.
        /// </summary>
        public static string FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดไฟล์.
        /// </summary>
        public static string FILE_SIZE {
            get {
                return ResourceManager.GetString("FILE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่บริษัทประกันภัย.
        /// </summary>
        public static string MS_CORP_ADDR1 {
            get {
                return ResourceManager.GetString("MS_CORP_ADDR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อบริษัทประกันภัย.
        /// </summary>
        public static string MS_CORP_NAME_TH {
            get {
                return ResourceManager.GetString("MS_CORP_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการหนังสือ/เอกสาร.
        /// </summary>
        public static string Panel_Grid {
            get {
                return ResourceManager.GetString("Panel_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลลายมือชื่ออิเล็กทรอนิกส์.
        /// </summary>
        public static string Panel_Header {
            get {
                return ResourceManager.GetString("Panel_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to งวดการรายงานข้อมูล.
        /// </summary>
        public static string PERIOD_NAME {
            get {
                return ResourceManager.GetString("PERIOD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้รับข้อมูล .
        /// </summary>
        public static string RECEIVE_BY_NAME_TH {
            get {
                return ResourceManager.GetString("RECEIVE_BY_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่รับ.
        /// </summary>
        public static string RECEIVE_DOC {
            get {
                return ResourceManager.GetString("RECEIVE_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันและเวลาที่รับข้อมูล .
        /// </summary>
        public static string RECEIVE_DT {
            get {
                return ResourceManager.GetString("RECEIVE_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขที่อ้างอิง.
        /// </summary>
        public static string REFERENCE_DOC {
            get {
                return ResourceManager.GetString("REFERENCE_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่วนย่อยเอกสาร.
        /// </summary>
        public static string SECTION_GROUP_NAME_TH {
            get {
                return ResourceManager.GetString("SECTION_GROUP_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้นำส่ง.
        /// </summary>
        public static string SEND_BY_TH {
            get {
                return ResourceManager.GetString("SEND_BY_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นำส่งครั้งที่.
        /// </summary>
        public static string SEND_NO {
            get {
                return ResourceManager.GetString("SEND_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลายมือชื่ออิเล็กทรอนิกส์.
        /// </summary>
        public static string SIGNATURE_SIGN {
            get {
                return ResourceManager.GetString("SIGNATURE_SIGN", resourceCulture);
            }
        }
    }
}
