//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.SEC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SECS02P002 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SECS02P002() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.SEC.SECS02P002", typeof(SECS02P002).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Application.
        /// </summary>
        public static string APP_CODE {
            get {
                return ResourceManager.GetString("APP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com Code.
        /// </summary>
        public static string COM_CODE {
            get {
                return ResourceManager.GetString("COM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Application Eng.
        /// </summary>
        public static string COM_CODE_E {
            get {
                return ResourceManager.GetString("COM_CODE_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Application Thai.
        /// </summary>
        public static string COM_CODE_T {
            get {
                return ResourceManager.GetString("COM_CODE_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string COM_NAME_E {
            get {
                return ResourceManager.GetString("COM_NAME_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DEPT_ID {
            get {
                return ResourceManager.GetString("DEPT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DEPT_NAME_TH {
            get {
                return ResourceManager.GetString("DEPT_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Address.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string FORGET_PWD {
            get {
                return ResourceManager.GetString("FORGET_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string IS_DISABLED {
            get {
                return ResourceManager.GetString("IS_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is Disabled.
        /// </summary>
        public static string IS_DISABLED_ADD {
            get {
                return ResourceManager.GetString("IS_DISABLED_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string MODULE {
            get {
                return ResourceManager.GetString("MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string PERMISSION {
            get {
                return ResourceManager.GetString("PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Criteria.
        /// </summary>
        public static string RE_PWD_CRITERIA {
            get {
                return ResourceManager.GetString("RE_PWD_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Active.
        /// </summary>
        public static string STATUS_DISBLE {
            get {
                return ResourceManager.GetString("STATUS_DISBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string STATUS_ENABLE {
            get {
                return ResourceManager.GetString("STATUS_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Name.
        /// </summary>
        public static string SUPPORT {
            get {
                return ResourceManager.GetString("SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string TELEPHONE {
            get {
                return ResourceManager.GetString("TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TITLE_ID {
            get {
                return ResourceManager.GetString("TITLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Name.
        /// </summary>
        public static string TITLE_NAME_TH {
            get {
                return ResourceManager.GetString("TITLE_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name (Eng).
        /// </summary>
        public static string USER_FNAME_EN {
            get {
                return ResourceManager.GetString("USER_FNAME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name (Th).
        /// </summary>
        public static string USER_FNAME_TH {
            get {
                return ResourceManager.GetString("USER_FNAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string USER_ID {
            get {
                return ResourceManager.GetString("USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name (Eng).
        /// </summary>
        public static string USER_LNAME_EN {
            get {
                return ResourceManager.GetString("USER_LNAME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name (Th).
        /// </summary>
        public static string USER_LNAME_TH {
            get {
                return ResourceManager.GetString("USER_LNAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string USER_PWD {
            get {
                return ResourceManager.GetString("USER_PWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string USER_PWD_NEW {
            get {
                return ResourceManager.GetString("USER_PWD_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string USER_PWD_OLD {
            get {
                return ResourceManager.GetString("USER_PWD_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string USER_PWD_R {
            get {
                return ResourceManager.GetString("USER_PWD_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal ID.
        /// </summary>
        public static string USER_SPEC_ID {
            get {
                return ResourceManager.GetString("USER_SPEC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string USER_STATUS {
            get {
                return ResourceManager.GetString("USER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string USG_ID {
            get {
                return ResourceManager.GetString("USG_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group ID.
        /// </summary>
        public static string USG_NAME_TH {
            get {
                return ResourceManager.GetString("USG_NAME_TH", resourceCulture);
            }
        }
    }
}
