//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.SEC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SECS01P003 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SECS01P003() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.SEC.SECS01P003", typeof(SECS01P003).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string PRG_ACTION {
            get {
                return ResourceManager.GetString("PRG_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string PRG_AREA {
            get {
                return ResourceManager.GetString("PRG_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Code.
        /// </summary>
        public static string PRG_CODE {
            get {
                return ResourceManager.GetString("PRG_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        public static string PRG_CONTROLLER {
            get {
                return ResourceManager.GetString("PRG_CONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Display.
        /// </summary>
        public static string PRG_IMG {
            get {
                return ResourceManager.GetString("PRG_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name (Eng).
        /// </summary>
        public static string PRG_NAME_EN {
            get {
                return ResourceManager.GetString("PRG_NAME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name (Th).
        /// </summary>
        public static string PRG_NAME_TH {
            get {
                return ResourceManager.GetString("PRG_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program No.
        /// </summary>
        public static string PRG_NO {
            get {
                return ResourceManager.GetString("PRG_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string PRG_PARAMETER {
            get {
                return ResourceManager.GetString("PRG_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PRG_STATUS {
            get {
                return ResourceManager.GetString("PRG_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Type.
        /// </summary>
        public static string PRG_TYPE {
            get {
                return ResourceManager.GetString("PRG_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL Program.
        /// </summary>
        public static string PRG_URL {
            get {
                return ResourceManager.GetString("PRG_URL", resourceCulture);
            }
        }
    }
}
