//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.SEC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SECS01P001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SECS01P001() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.SEC.SECS01P001", typeof(SECS01P001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Eng).
        /// </summary>
        public static string Address_Eng {
            get {
                return ResourceManager.GetString("Address_Eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Th).
        /// </summary>
        public static string Address_T {
            get {
                return ResourceManager.GetString("Address_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Module.
        /// </summary>
        public static string COGF_MODULE {
            get {
                return ResourceManager.GetString("COGF_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 (Eng).
        /// </summary>
        public static string COM_ADDR1_E {
            get {
                return ResourceManager.GetString("COM_ADDR1_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 (Th).
        /// </summary>
        public static string COM_ADDR1_T {
            get {
                return ResourceManager.GetString("COM_ADDR1_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2 (Eng).
        /// </summary>
        public static string COM_ADDR2_E {
            get {
                return ResourceManager.GetString("COM_ADDR2_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2 (Th).
        /// </summary>
        public static string COM_ADDR2_T {
            get {
                return ResourceManager.GetString("COM_ADDR2_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub District (Eng).
        /// </summary>
        public static string COM_AMPHUR_E {
            get {
                return ResourceManager.GetString("COM_AMPHUR_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub District (Th).
        /// </summary>
        public static string COM_AMPHUR_T {
            get {
                return ResourceManager.GetString("COM_AMPHUR_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Code .
        /// </summary>
        public static string COM_BRANCH {
            get {
                return ResourceManager.GetString("COM_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name .
        /// </summary>
        public static string COM_BRANCH_E {
            get {
                return ResourceManager.GetString("COM_BRANCH_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch (Eng).
        /// </summary>
        public static string COM_BRANCH_E1 {
            get {
                return ResourceManager.GetString("COM_BRANCH_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch (Th).
        /// </summary>
        public static string COM_BRANCH_T {
            get {
                return ResourceManager.GetString("COM_BRANCH_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code .
        /// </summary>
        public static string COM_CODE {
            get {
                return ResourceManager.GetString("COM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District (Eng).
        /// </summary>
        public static string COM_DISTRICT_E {
            get {
                return ResourceManager.GetString("COM_DISTRICT_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District (Th).
        /// </summary>
        public static string COM_DISTRICT_T {
            get {
                return ResourceManager.GetString("COM_DISTRICT_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string COM_E_MAIL {
            get {
                return ResourceManager.GetString("COM_E_MAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 (Eng).
        /// </summary>
        public static string COM_FAC_ADDR1_E {
            get {
                return ResourceManager.GetString("COM_FAC_ADDR1_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1 (Th).
        /// </summary>
        public static string COM_FAC_ADDR1_T {
            get {
                return ResourceManager.GetString("COM_FAC_ADDR1_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2 (Eng).
        /// </summary>
        public static string COM_FAC_ADDR2_E {
            get {
                return ResourceManager.GetString("COM_FAC_ADDR2_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2 (Th).
        /// </summary>
        public static string COM_FAC_ADDR2_T {
            get {
                return ResourceManager.GetString("COM_FAC_ADDR2_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District (Eng).
        /// </summary>
        public static string COM_FAC_AMP_E {
            get {
                return ResourceManager.GetString("COM_FAC_AMP_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District (Th).
        /// </summary>
        public static string COM_FAC_AMP_T {
            get {
                return ResourceManager.GetString("COM_FAC_AMP_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub District (Eng).
        /// </summary>
        public static string COM_FAC_DISTRICT_E {
            get {
                return ResourceManager.GetString("COM_FAC_DISTRICT_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub District (Th).
        /// </summary>
        public static string COM_FAC_DISTRICT_T {
            get {
                return ResourceManager.GetString("COM_FAC_DISTRICT_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Name (Eng).
        /// </summary>
        public static string COM_FAC_NAME_E {
            get {
                return ResourceManager.GetString("COM_FAC_NAME_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Name (Th).
        /// </summary>
        public static string COM_FAC_NAME_T {
            get {
                return ResourceManager.GetString("COM_FAC_NAME_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code (Eng).
        /// </summary>
        public static string COM_FAC_POST_E {
            get {
                return ResourceManager.GetString("COM_FAC_POST_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code (Th).
        /// </summary>
        public static string COM_FAC_POST_T {
            get {
                return ResourceManager.GetString("COM_FAC_POST_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province (Eng).
        /// </summary>
        public static string COM_FAC_PRV_E {
            get {
                return ResourceManager.GetString("COM_FAC_PRV_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province (Th).
        /// </summary>
        public static string COM_FAC_PRV_T {
            get {
                return ResourceManager.GetString("COM_FAC_PRV_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road (Eng).
        /// </summary>
        public static string COM_FAC_ROAD_E {
            get {
                return ResourceManager.GetString("COM_FAC_ROAD_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road (Th).
        /// </summary>
        public static string COM_FAC_ROAD_T {
            get {
                return ResourceManager.GetString("COM_FAC_ROAD_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soi (Eng).
        /// </summary>
        public static string COM_FAC_SOI_E {
            get {
                return ResourceManager.GetString("COM_FAC_SOI_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soi (Th).
        /// </summary>
        public static string COM_FAC_SOI_T {
            get {
                return ResourceManager.GetString("COM_FAC_SOI_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string COM_FAX_NO {
            get {
                return ResourceManager.GetString("COM_FAX_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Data Manufacturer Data.
        /// </summary>
        public static string COM_HEADER {
            get {
                return ResourceManager.GetString("COM_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License ID.
        /// </summary>
        public static string COM_LICENSE_ID {
            get {
                return ResourceManager.GetString("COM_LICENSE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name (Eng).
        /// </summary>
        public static string COM_NAME_E {
            get {
                return ResourceManager.GetString("COM_NAME_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name (Eng).
        /// </summary>
        public static string COM_NAME_SHORT_E {
            get {
                return ResourceManager.GetString("COM_NAME_SHORT_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name (Th).
        /// </summary>
        public static string COM_NAME_SHORT_T {
            get {
                return ResourceManager.GetString("COM_NAME_SHORT_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name (Th).
        /// </summary>
        public static string COM_NAME_T {
            get {
                return ResourceManager.GetString("COM_NAME_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code (Eng).
        /// </summary>
        public static string COM_POST_CODE_E {
            get {
                return ResourceManager.GetString("COM_POST_CODE_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code (Th).
        /// </summary>
        public static string COM_POST_CODE_T {
            get {
                return ResourceManager.GetString("COM_POST_CODE_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province (Eng).
        /// </summary>
        public static string COM_PROVINCE_E {
            get {
                return ResourceManager.GetString("COM_PROVINCE_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province (Th).
        /// </summary>
        public static string COM_PROVINCE_T {
            get {
                return ResourceManager.GetString("COM_PROVINCE_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road (Eng).
        /// </summary>
        public static string COM_ROAD_E {
            get {
                return ResourceManager.GetString("COM_ROAD_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road (Th).
        /// </summary>
        public static string COM_ROAD_T {
            get {
                return ResourceManager.GetString("COM_ROAD_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soi (Eng).
        /// </summary>
        public static string COM_SOI_E {
            get {
                return ResourceManager.GetString("COM_SOI_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soi (Th).
        /// </summary>
        public static string COM_SOI_T {
            get {
                return ResourceManager.GetString("COM_SOI_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX ID.
        /// </summary>
        public static string COM_TAX_ID {
            get {
                return ResourceManager.GetString("COM_TAX_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string COM_TEL_NO {
            get {
                return ResourceManager.GetString("COM_TEL_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string COM_USE_LANGUAGE {
            get {
                return ResourceManager.GetString("COM_USE_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string MODULE {
            get {
                return ResourceManager.GetString("MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Name.
        /// </summary>
        public static string USER_ID {
            get {
                return ResourceManager.GetString("USER_ID", resourceCulture);
            }
        }
    }
}
