//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.SEC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SECS02P001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SECS02P001() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.SEC.SECS02P001", typeof(SECS02P001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Code.
        /// </summary>
        public static string PRG_CODE {
            get {
                return ResourceManager.GetString("PRG_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name.
        /// </summary>
        public static string PRG_NAME {
            get {
                return ResourceManager.GetString("PRG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Program Permission.
        /// </summary>
        public static string SetProgramPermission {
            get {
                return ResourceManager.GetString("SetProgramPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting Program Sequence.
        /// </summary>
        public static string SortProgramSequence {
            get {
                return ResourceManager.GetString("SortProgramSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting System Sequence.
        /// </summary>
        public static string SortSystemSequence {
            get {
                return ResourceManager.GetString("SortSystemSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Code.
        /// </summary>
        public static string SYS_CODE {
            get {
                return ResourceManager.GetString("SYS_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Group Name.
        /// </summary>
        public static string SYS_GROUP_NAME {
            get {
                return ResourceManager.GetString("SYS_GROUP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name.
        /// </summary>
        public static string SYS_NAME {
            get {
                return ResourceManager.GetString("SYS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set permission to user group.
        /// </summary>
        public static string TitleSetPermissionToUsg {
            get {
                return ResourceManager.GetString("TitleSetPermissionToUsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User group detail.
        /// </summary>
        public static string TitleUsgDetail {
            get {
                return ResourceManager.GetString("TitleUsgDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Code.
        /// </summary>
        public static string USG_CODE {
            get {
                return ResourceManager.GetString("USG_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string USG_LEVEL {
            get {
                return ResourceManager.GetString("USG_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name (EN).
        /// </summary>
        public static string USG_NAME_EN {
            get {
                return ResourceManager.GetString("USG_NAME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name (TH).
        /// </summary>
        public static string USG_NAME_TH {
            get {
                return ResourceManager.GetString("USG_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string USG_STATUS {
            get {
                return ResourceManager.GetString("USG_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string USG_STATUS_Active {
            get {
                return ResourceManager.GetString("USG_STATUS_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Active.
        /// </summary>
        public static string USG_STATUS_NonActive {
            get {
                return ResourceManager.GetString("USG_STATUS_NonActive", resourceCulture);
            }
        }
    }
}
