//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AATEntities : DbContext
    {
        public AATEntities()
            : base("name=AATEntities")
        {
        }
    
    	public AATEntities(string connection)
            : base(connection)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VSMS_EXCEL_DETAIL> VSMS_EXCEL_DETAIL { get; set; }
        public virtual DbSet<VSMS_PROGRAM> VSMS_PROGRAM { get; set; }
        public virtual DbSet<VSMS_CONFIG_GENERAL> VSMS_CONFIG_GENERAL { get; set; }
        public virtual DbSet<VSMS_SYSTEM> VSMS_SYSTEM { get; set; }
        public virtual DbSet<VSMS_CTRLLOG> VSMS_CTRLLOG { get; set; }
        public virtual DbSet<VSMS_USRGROUP> VSMS_USRGROUP { get; set; }
        public virtual DbSet<VSMS_COMPANY> VSMS_COMPANY { get; set; }
        public virtual DbSet<VSMS_TITLE> VSMS_TITLE { get; set; }
        public virtual DbSet<VSMS_CONFIG_FTP> VSMS_CONFIG_FTP { get; set; }
        public virtual DbSet<VSMS_CONFIG_SYS> VSMS_CONFIG_SYS { get; set; }
        public virtual DbSet<VSMS_USER> VSMS_USER { get; set; }
        public virtual DbSet<VSMS_USERCOM> VSMS_USERCOM { get; set; }
        public virtual DbSet<VSMS_EXCEL> VSMS_EXCEL { get; set; }
        public virtual DbSet<VSMS_SYS_PGC> VSMS_SYS_PGC { get; set; }
        public virtual DbSet<VSMS_NOTIFICATION> VSMS_NOTIFICATION { get; set; }
        public virtual DbSet<VSMS_ISSUE> VSMS_ISSUE { get; set; }
        public virtual DbSet<VSMS_MODULE> VSMS_MODULE { get; set; }
        public virtual DbSet<VSMS_USRGRPPRIV> VSMS_USRGRPPRIV { get; set; }
    }
}
