//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSMS_NOTIFICATION
    {
        public string COM_CODE { get; set; }
        public decimal NTF_KEY { get; set; }
        public string USER_ID { get; set; }
        public string DETAIL { get; set; }
        public string FLAG { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<System.DateTime> CRET_DATE { get; set; }
        public Nullable<System.DateTime> MNT_DATE { get; set; }
        public decimal NO { get; set; }
    }
}
