//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSMS_SYSTEM
    {
        public string COM_CODE { get; set; }
        public string SYS_CODE { get; set; }
        public Nullable<decimal> SYS_SEQ { get; set; }
        public string SYS_NAME_TH { get; set; }
        public string SYS_NAME_EN { get; set; }
        public string SYS_STATUS { get; set; }
        public string CRET_BY { get; set; }
        public Nullable<System.DateTime> CRET_DATE { get; set; }
        public string MNT_BY { get; set; }
        public Nullable<System.DateTime> MNT_DATE { get; set; }
    }
}
