//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSMS_COMPANY
    {
        public string COM_CODE { get; set; }
        public string BOND_NO { get; set; }
        public string COM_BRANCH { get; set; }
        public string COM_NAME_T { get; set; }
        public string COM_FAC_NAME_T { get; set; }
        public string COM_NAME_E { get; set; }
        public string COM_FAC_NAME_E { get; set; }
        public string COM_BRANCH_T { get; set; }
        public string COM_BRANCH_E { get; set; }
        public string COM_ADDR1_T { get; set; }
        public string COM_ADDR2_T { get; set; }
        public string COM_SOI_T { get; set; }
        public string COM_ROAD_T { get; set; }
        public string COM_DISTRICT_T { get; set; }
        public string COM_AMPHUR_T { get; set; }
        public string COM_PROVINCE_T { get; set; }
        public string COM_ADDR1_E { get; set; }
        public string COM_ADDR2_E { get; set; }
        public string COM_SOI_E { get; set; }
        public string COM_ROAD_E { get; set; }
        public string COM_DISTRICT_E { get; set; }
        public string COM_AMPHUR_E { get; set; }
        public string COM_PROVINCE_E { get; set; }
        public string COM_POST_CODE { get; set; }
        public string COM_FAC_ADDR1_T { get; set; }
        public string COM_FAC_ADDR2_T { get; set; }
        public string COM_FAC_SOI_T { get; set; }
        public string COM_FAC_ROAD_T { get; set; }
        public string COM_FAC_DISTRICT_T { get; set; }
        public string COM_FAC_AMP_T { get; set; }
        public string COM_FAC_PRV_T { get; set; }
        public string COM_FAC_ADDR1_E { get; set; }
        public string COM_FAC_ADDR2_E { get; set; }
        public string COM_FAC_SOI_E { get; set; }
        public string COM_FAC_ROAD_E { get; set; }
        public string COM_FAC_DISTRICT_E { get; set; }
        public string COM_FAC_AMP_E { get; set; }
        public string COM_FAC_PRV_E { get; set; }
        public string COM_FAC_POST { get; set; }
        public string COM_TEL_NO { get; set; }
        public string COM_FAX_NO { get; set; }
        public string COM_E_MAIL { get; set; }
        public string COM_NAME_SHORT_T { get; set; }
        public string COM_NAME_SHORT_E { get; set; }
        public string COM_LICENSE_ID { get; set; }
        public string COM_TAX_ID { get; set; }
        public string COM_USE_LANGUAGE { get; set; }
        public string CRET_BY { get; set; }
        public Nullable<System.DateTime> CRET_DATE { get; set; }
        public string MNT_BY { get; set; }
        public Nullable<System.DateTime> MNT_DATE { get; set; }
    }
}
