//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSMS_USRGRPPRIV
    {
        public string COM_CODE { get; set; }
        public Nullable<decimal> USG_ID { get; set; }
        public decimal USRGRPPRIV_ID { get; set; }
        public string USG_LEVEL { get; set; }
        public string SYS_CODE { get; set; }
        public string PRG_CODE { get; set; }
        public Nullable<decimal> SYS_SEQ { get; set; }
        public Nullable<decimal> PRG_SEQ { get; set; }
        public string ROLE_SEARCH { get; set; }
        public string ROLE_ADD { get; set; }
        public string ROLE_EDIT { get; set; }
        public string ROLE_DEL { get; set; }
        public string ROLE_PRINT { get; set; }
        public string SYS_STATUS { get; set; }
        public string PRG_STATUS { get; set; }
        public string CRET_BY { get; set; }
        public Nullable<System.DateTime> CRET_DATE { get; set; }
        public string MNT_BY { get; set; }
        public Nullable<System.DateTime> MNT_DATE { get; set; }
    }
}
