//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSMS_EXCEL_DETAIL
    {
        public string COM_CODE { get; set; }
        public string PRG_CODE { get; set; }
        public string COL_NAME { get; set; }
        public int LIST_NO { get; set; }
        public Nullable<int> COL_TYPE { get; set; }
        public Nullable<int> RATIO { get; set; }
        public string FLG_USE { get; set; }
        public string ISNULL { get; set; }
        public string FORMAT_STYLE { get; set; }
        public string CULTULE_STYLE { get; set; }
        public string DB_COLUMN { get; set; }
        public string MAX_LENGTH { get; set; }
        public string IS_VALIDATE { get; set; }
        public string IS_SAVE { get; set; }
        public string CRET_BY { get; set; }
        public Nullable<System.DateTime> CRET_DATE { get; set; }
        public string MNT_BY { get; set; }
        public Nullable<System.DateTime> MNT_DATE { get; set; }
    }
}
