//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSMS_USER
    {
        public string COM_CODE { get; set; }
        public string USER_ID { get; set; }
        public string USER_FNAME_TH { get; set; }
        public string USER_LNAME_TH { get; set; }
        public string USER_FNAME_EN { get; set; }
        public string USER_LNAME_EN { get; set; }
        public Nullable<decimal> TITLE_ID { get; set; }
        public Nullable<decimal> USG_ID { get; set; }
        public string USER_PWD { get; set; }
        public string TELEPHONE { get; set; }
        public string EMAIL { get; set; }
        public string USER_STATUS { get; set; }
        public string IS_DISABLED { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_DATE { get; set; }
        public string CRET_BY { get; set; }
        public Nullable<System.DateTime> CRET_DATE { get; set; }
        public string MNT_BY { get; set; }
        public Nullable<System.DateTime> MNT_DATE { get; set; }
        public string DEPARTMENT { get; set; }
    }
}
