//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSMS_PROGRAM
    {
        public string COM_CODE { get; set; }
        public string PRG_CODE { get; set; }
        public string PRG_NAME_TH { get; set; }
        public string PRG_NAME_EN { get; set; }
        public string PRG_TYPE { get; set; }
        public Nullable<decimal> PRG_LEVEL { get; set; }
        public string PRG_STATUS { get; set; }
        public string PRG_URL { get; set; }
        public string PRG_IMG { get; set; }
        public string PRG_AREA { get; set; }
        public string PRG_CONTROLLER { get; set; }
        public string PRG_ACTION { get; set; }
        public string PRG_PARAMETER { get; set; }
        public string CRET_BY { get; set; }
        public Nullable<System.DateTime> CRET_DATE { get; set; }
        public string MNT_BY { get; set; }
        public Nullable<System.DateTime> MNT_DATE { get; set; }
    }
}
