//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSMS_CONFIG_GENERAL
    {
        public string COM_CODE { get; set; }
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public string SYS_CODE { get; set; }
        public string STR_VALUE { get; set; }
        public Nullable<int> INT_VALUE { get; set; }
        public Nullable<decimal> DEC_VALUE { get; set; }
        public string IMG { get; set; }
        public string IMG_COLOR { get; set; }
    }
}
