//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSMS_ISSUE
    {
        public string COM_CODE { get; set; }
        public decimal NO { get; set; }
        public Nullable<decimal> REF_NO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public string ISSUE_DATE_PERIOD { get; set; }
        public string MODULE { get; set; }
        public string DETAIL { get; set; }
        public string ROOT_CAUSE { get; set; }
        public string SOLUTION { get; set; }
        public string EFFECTS { get; set; }
        public string ISSUE_BY { get; set; }
        public string RESPONSE_BY { get; set; }
        public Nullable<System.DateTime> TARGET_DATE { get; set; }
        public Nullable<System.DateTime> RESPONSE_DATE { get; set; }
        public string ACTUAL_RESTIME { get; set; }
        public string RESPONSE_TARGET { get; set; }
        public string ACTUAL_RESTIME_QA { get; set; }
        public string ACTUAL_RESTIME_PD { get; set; }
        public string ACTUAL_RESTIME_CL { get; set; }
        public string RESOLUTION_TARGET { get; set; }
        public Nullable<System.DateTime> DEPLOY_QA { get; set; }
        public Nullable<System.DateTime> DEPLOY_PD { get; set; }
        public string FILE_ID { get; set; }
        public string ESSR_NO { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public string ISSUE_TYPE { get; set; }
        public string DEFECT { get; set; }
        public string PRIORITY { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> MAN_PLM_SA { get; set; }
        public Nullable<decimal> MAN_PLM_QA { get; set; }
        public Nullable<decimal> MAN_PLM_PRG { get; set; }
        public Nullable<decimal> MAN_PLM_PL { get; set; }
        public string MAN_PLM_DBA { get; set; }
        public string ISSUE_IMG { get; set; }
        public string ASSIGN_USER { get; set; }
        public string CRET_BY { get; set; }
        public Nullable<System.DateTime> CRET_DATE { get; set; }
        public string MNT_BY { get; set; }
        public Nullable<System.DateTime> MNT_DATE { get; set; }
    }
}
