//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.MST {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MSTS03P001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSTS03P001() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.MST.MSTS03P001", typeof(MSTS03P001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App.
        /// </summary>
        public static string APP_CODE1 {
            get {
                return ResourceManager.GetString("APP_CODE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No charge.
        /// </summary>
        public static string IS_FREE {
            get {
                return ResourceManager.GetString("IS_FREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Type.
        /// </summary>
        public static string ISSUE_TYPE {
            get {
                return ResourceManager.GetString("ISSUE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string KEY_ID {
            get {
                return ResourceManager.GetString("KEY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Criteria.
        /// </summary>
        public static string PRIORITY_CRITERIA {
            get {
                return ResourceManager.GetString("PRIORITY_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Name.
        /// </summary>
        public static string PRIORITY_NAME {
            get {
                return ResourceManager.GetString("PRIORITY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string REMASK {
            get {
                return ResourceManager.GetString("REMASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Time.
        /// </summary>
        public static string RES_TIME {
            get {
                return ResourceManager.GetString("RES_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Type.
        /// </summary>
        public static string RES_TYPE {
            get {
                return ResourceManager.GetString("RES_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Resolution Time.
        /// </summary>
        public static string T_RES_TIME {
            get {
                return ResourceManager.GetString("T_RES_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Type.
        /// </summary>
        public static string T_RES_TYPE {
            get {
                return ResourceManager.GetString("T_RES_TYPE", resourceCulture);
            }
        }
    }
}
