//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.MST {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MSTS01P001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSTS01P001() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.MST.MSTS01P001", typeof(MSTS01P001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string IS_USE {
            get {
                return ResourceManager.GetString("IS_USE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        public static string ISSUE_TYPE {
            get {
                return ResourceManager.GetString("ISSUE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Rate of MA Waranty Criteria.
        /// </summary>
        public static string MA_CRITERIA {
            get {
                return ResourceManager.GetString("MA_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer.
        /// </summary>
        public static string MAN_PLM_PRG {
            get {
                return ResourceManager.GetString("MAN_PLM_PRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA &amp; Support Desk.
        /// </summary>
        public static string MAN_PLM_QA {
            get {
                return ResourceManager.GetString("MAN_PLM_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA &amp; Lead Support.
        /// </summary>
        public static string MAN_PLM_SA {
            get {
                return ResourceManager.GetString("MAN_PLM_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Rate.
        /// </summary>
        public static string TYPE_RATE {
            get {
                return ResourceManager.GetString("TYPE_RATE", resourceCulture);
            }
        }
    }
}
