//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.CenterLang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Center {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Center() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.CenterLang.Center", typeof(Center).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณไม่มีสิทธิเข้าใช้งานระบบ  กรุณาติดต่อผู้ดูแลระบบ คปภ..
        /// </summary>
        public static string AccessDeniedSignIn {
            get {
                return ResourceManager.GetString("AccessDeniedSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มไฟล์.
        /// </summary>
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสแอพพลิเคชั่น.
        /// </summary>
        public static string APP_CODE {
            get {
                return ResourceManager.GetString("APP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนไฟล์แนบเกินกว่าที่ระบบกำหนด.
        /// </summary>
        public static string AttachFileMaximumLimit {
            get {
                return ResourceManager.GetString("AttachFileMaximumLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดไฟล์แนบรวมเกินกว่าที่ระบบกำหนด.
        /// </summary>
        public static string AttachFileMaximumSizeLimit {
            get {
                return ResourceManager.GetString("AttachFileMaximumSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ย้อนกลับ.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เรียกดูรายงาน.
        /// </summary>
        public static string CallReport {
            get {
                return ResourceManager.GetString("CallReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิก.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกข้อมูลสำเร็จ.
        /// </summary>
        public static string CancelCompleted {
            get {
                return ResourceManager.GetString("CancelCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกร่าง.
        /// </summary>
        public static string CancelDraft {
            get {
                return ResourceManager.GetString("CancelDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกข้อมูลไม่สำเร็จ.
        /// </summary>
        public static string CancelNotComplete {
            get {
                return ResourceManager.GetString("CancelNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ปิดหน้าจอ.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to log out and close browser?.
        /// </summary>
        public static string CLOSE_BROWSER {
            get {
                return ResourceManager.GetString("CLOSE_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อบริษัท.
        /// </summary>
        public static string COM_CODE {
            get {
                return ResourceManager.GetString("COM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อแอพพลิเคชั่น.
        /// </summary>
        public static string COM_NAME {
            get {
                return ResourceManager.GetString("COM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อแอพพลิเคชั่นภาษาไทย.
        /// </summary>
        public static string COM_NAME_E {
            get {
                return ResourceManager.GetString("COM_NAME_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อแอพพลิเคชั่นภาษาอังกฤษ.
        /// </summary>
        public static string COM_NAME_T {
            get {
                return ResourceManager.GetString("COM_NAME_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดบริษัท.
        /// </summary>
        public static string ConfigInsuranceCompany {
            get {
                return ResourceManager.GetString("ConfigInsuranceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดโปรแกรม.
        /// </summary>
        public static string ConfigProgram {
            get {
                return ResourceManager.GetString("ConfigProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำหนดผู้ใช้งาน.
        /// </summary>
        public static string ConfigUser {
            get {
                return ResourceManager.GetString("ConfigUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยัน.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการยกเลิกข้อมูลร่างหรือไม่?.
        /// </summary>
        public static string CONFIRM_CANCEL_DRAFT {
            get {
                return ResourceManager.GetString("CONFIRM_CANCEL_DRAFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการยกเลิกหรือไม่?.
        /// </summary>
        public static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการล้างหน้าจอหรือไม่?.
        /// </summary>
        public static string ConfirmClear {
            get {
                return ResourceManager.GetString("ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องปิดหน้านี้หรือไหม?.
        /// </summary>
        public static string ConfirmClosePage {
            get {
                return ResourceManager.GetString("ConfirmClosePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Completed.
        /// </summary>
        public static string ConfirmCompleted {
            get {
                return ResourceManager.GetString("ConfirmCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการลบหรือไม่?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการพิจารณา.
        /// </summary>
        public static string ConfirmedConsideration {
            get {
                return ResourceManager.GetString("ConfirmedConsideration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการ_confirmText_หรือไหม?.
        /// </summary>
        public static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันนำส่ง.
        /// </summary>
        public static string ConfirmSending {
            get {
                return ResourceManager.GetString("ConfirmSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ติดต่อเรา.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คัดลอก.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ©️2018 AUTOALLIANCE (Thailand). All Right reserved..
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผู้สร้างข้อมูล.
        /// </summary>
        public static string CRET_BY {
            get {
                return ResourceManager.GetString("CRET_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้สร้างข้อมูล.
        /// </summary>
        public static string CRET_BY_NAME_TH {
            get {
                return ResourceManager.GetString("CRET_BY_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่สร้างข้อมูล.
        /// </summary>
        public static string CRET_DATE {
            get {
                return ResourceManager.GetString("CRET_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยกเลิกข้อมูล.
        /// </summary>
        public static string DATA_CANCELLATION {
            get {
                return ResourceManager.GetString("DATA_CANCELLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีข้อมูล.
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบ.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูลสำเร็จ.
        /// </summary>
        public static string DeleteCompleted {
            get {
                return ResourceManager.GetString("DeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบไฟล์.
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลบข้อมูลไม่สำเร็จ.
        /// </summary>
        public static string DeleteNotComplete {
            get {
                return ResourceManager.GetString("DeleteNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียด.
        /// </summary>
        public static string DETAIL {
            get {
                return ResourceManager.GetString("DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลด.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลดซิปไฟล์.
        /// </summary>
        public static string Download_zip_file {
            get {
                return ResourceManager.GetString("Download_zip_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Completed.
        /// </summary>
        public static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดาวน์โหลดรูปแบบนำเข้า.
        /// </summary>
        public static string DownloadTemplate {
            get {
                return ResourceManager.GetString("DownloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณต้องการกลับไปหน้าเริ่มต้นหรือไม่?.
        /// </summary>
        public static string DoYouWantGoToHome {
            get {
                return ResourceManager.GetString("DoYouWantGoToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลซ้ำกัน.
        /// </summary>
        public static string DuplcateData {
            get {
                return ResourceManager.GetString("DuplcateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แก้ไข.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อังกฤษ.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Data.
        /// </summary>
        public static string EXCEL_UPLOAD {
            get {
                return ResourceManager.GetString("EXCEL_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออก.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำถามที่พบบ่อย.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบไฟล์ข้อมูล.
        /// </summary>
        public static string FILE_DOWNLOAD_NOTFOUND {
            get {
                return ResourceManager.GetString("FILE_DOWNLOAD_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบไฟล์ซ้ำ กรุณาตรวจสอบไฟล์ที่ระบุ.
        /// </summary>
        public static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน/เวลา เอกสาร.
        /// </summary>
        public static string FileDateModified {
            get {
                return ResourceManager.GetString("FileDateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดไฟล์แนบรวมเกินกว่าที่ระบบกำหนด.
        /// </summary>
        public static string FileMaximumSizeLimit {
            get {
                return ResourceManager.GetString("FileMaximumSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อไฟล์.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบไฟล์ที่ไม่ได้กำหนดในระบบ กรุณาตรวจสอบไฟล์ที่ระบุ.
        /// </summary>
        public static string FileNotExistsSystemConfig {
            get {
                return ResourceManager.GetString("FileNotExistsSystemConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่พบไฟล์ข้อมูล.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขนาดไฟล์.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รูปแบบไฟล์.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัน/เวลาที่ Upload.
        /// </summary>
        public static string FileUploadDate {
            get {
                return ResourceManager.GetString("FileUploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รอ Upload.
        /// </summary>
        public static string FileWaitingUpload {
            get {
                return ResourceManager.GetString("FileWaitingUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันส่งข้อมูล.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าแรก.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ลืมรหัสผ่าน.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- ไม่พบข้อมูล ----.
        /// </summary>
        public static string gridEmptyTable {
            get {
                return ResourceManager.GetString("gridEmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดง _START_ ถึง _END_ จาก _TOTAL_ รายการ.
        /// </summary>
        public static string gridInfo {
            get {
                return ResourceManager.GetString("gridInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดง 0 ถึง 0 จาก 0 รายการ.
        /// </summary>
        public static string gridInfoEmpty {
            get {
                return ResourceManager.GetString("gridInfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (กรองทั้งหมดจาก _MAX_ รายการ).
        /// </summary>
        public static string gridInfoFiltered {
            get {
                return ResourceManager.GetString("gridInfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แสดง _MENU_.
        /// </summary>
        public static string gridLengthMenu {
            get {
                return ResourceManager.GetString("gridLengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string gridLoadingRecords {
            get {
                return ResourceManager.GetString("gridLoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าแรก.
        /// </summary>
        public static string gridPaginateFirst {
            get {
                return ResourceManager.GetString("gridPaginateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าสุดท้าย.
        /// </summary>
        public static string gridPaginateLast {
            get {
                return ResourceManager.GetString("gridPaginateLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถัดไป.
        /// </summary>
        public static string gridPaginateNext {
            get {
                return ResourceManager.GetString("gridPaginateNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ก่อนหน้า.
        /// </summary>
        public static string gridPaginatePrevious {
            get {
                return ResourceManager.GetString("gridPaginatePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กำลังประมวลผล....
        /// </summary>
        public static string gridProcessing {
            get {
                return ResourceManager.GetString("gridProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สวัสดี.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พบปัญหาการใช้งาน กรุณาติดต่อ Help Desk โทร..
        /// </summary>
        public static string HelpDesk {
            get {
                return ResourceManager.GetString("HelpDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประวัติ.
        /// </summary>
        public static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียด.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [กรุณากรอกข้อมูล].
        /// </summary>
        public static string InputPlaceholderRequired {
            get {
                return ResourceManager.GetString("InputPlaceholderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลบริษัทประกันภัย.
        /// </summary>
        public static string InsuranceCompanyDetail {
            get {
                return ResourceManager.GetString("InsuranceCompanyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันรับรายงานปัญหา.
        /// </summary>
        public static string ISSUE_DATE {
            get {
                return ResourceManager.GetString("ISSUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษา.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าสุดท้าย.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File.
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าสู่ระบบ.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ออกจากระบบ.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to น้าหลัก/เมนู.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสผู้แก้ไขข้อมูลล่าสุด.
        /// </summary>
        public static string MNT_BY {
            get {
                return ResourceManager.GetString("MNT_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้แก้ไขข้อมูลล่าสุด.
        /// </summary>
        public static string MNT_BY_NAME_TH {
            get {
                return ResourceManager.GetString("MNT_BY_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่แก้ไขข้อมูลล่าสุด.
        /// </summary>
        public static string MNT_DATE {
            get {
                return ResourceManager.GetString("MNT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โมดูล.
        /// </summary>
        public static string MODULE {
            get {
                return ResourceManager.GetString("MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อ่านต่อ.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ถัดไป.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ใช่.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ใช้งาน.
        /// </summary>
        public static string NOT_USING {
            get {
                return ResourceManager.GetString("NOT_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตกลง.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดบันทึกข้อมูล.
        /// </summary>
        public static string PleaseSaveData {
            get {
                return ResourceManager.GetString("PleaseSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุข้อมูล.
        /// </summary>
        public static string PleaseSelectData {
            get {
                return ResourceManager.GetString("PleaseSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาระบุกลุ่มรายงาน.
        /// </summary>
        public static string PleaseSelectReportGroup {
            get {
                return ResourceManager.GetString("PleaseSelectReportGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to โปรดระบุ.
        /// </summary>
        public static string PleaseSpecify {
            get {
                return ResourceManager.GetString("PleaseSpecify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ก่อนหน้า.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิมพ์รายงาน.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นโยบายความเป็นส่วนตัว.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string PROCESS_COMPLETE {
            get {
                return ResourceManager.GetString("PROCESS_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        public static string PROCESS_INCOMPLETE {
            get {
                return ResourceManager.GetString("PROCESS_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string PROCESS_PROCESSING {
            get {
                return ResourceManager.GetString("PROCESS_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string PROCESS_WAITING {
            get {
                return ResourceManager.GetString("PROCESS_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string PROCESS_WARNING {
            get {
                return ResourceManager.GetString("PROCESS_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Complete.
        /// </summary>
        public static string ProcessComplete {
            get {
                return ResourceManager.GetString("ProcessComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Not Complete.
        /// </summary>
        public static string ProcessNotComplete {
            get {
                return ResourceManager.GetString("ProcessNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to สมัครสมาชิก.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายงาน.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดกลุ่มรายงาน.
        /// </summary>
        public static string ReportGroupDetail {
            get {
                return ResourceManager.GetString("ReportGroupDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ล้างหน้าจอ.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้ตอบกลับ.
        /// </summary>
        public static string RESPONSE_BY {
            get {
                return ResourceManager.GetString("RESPONSE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึก.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกและยืนยันนำส่ง.
        /// </summary>
        public static string SaveAndConfirm {
            get {
                return ResourceManager.GetString("SaveAndConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลสำเร็จ.
        /// </summary>
        public static string SaveCompleted {
            get {
                return ResourceManager.GetString("SaveCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกและทำต่อ.
        /// </summary>
        public static string SaveContinue {
            get {
                return ResourceManager.GetString("SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกหน้านี้.
        /// </summary>
        public static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกแล้วเริ่มใหม่.
        /// </summary>
        public static string SaveNew {
            get {
                return ResourceManager.GetString("SaveNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกและทำต่อ.
        /// </summary>
        public static string SaveNext {
            get {
                return ResourceManager.GetString("SaveNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูลไม่สำเร็จ.
        /// </summary>
        public static string SaveNotComplete {
            get {
                return ResourceManager.GetString("SaveNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกรับหลักทรัพย์.
        /// </summary>
        public static string SaveReceivedAsset {
            get {
                return ResourceManager.GetString("SaveReceivedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [กรุณาเลือก].
        /// </summary>
        public static string SelectDefaultRequired {
            get {
                return ResourceManager.GetString("SelectDefaultRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ทั้งหมด].
        /// </summary>
        public static string SelectDefaultSearch {
            get {
                return ResourceManager.GetString("SelectDefaultSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ขั้นตอนที่.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดำเนินการ.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รองรับไฟล์ {tplFileType} เท่านั้น.
        /// </summary>
        public static string SupportFileType {
            get {
                return ResourceManager.GetString("SupportFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ระบบ.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขและข้อกำหนดการใช้บริการทางอินเทอร์เน็ตของ ออโต้อัลลายแอนซ์ (ประเทศไทย) จำกัด.
        /// </summary>
        public static string TermsofService {
            get {
                return ResourceManager.GetString("TermsofService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขและข้อกำหนดการใช้บริการ.
        /// </summary>
        public static string TermsofServiceF {
            get {
                return ResourceManager.GetString("TermsofServiceF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไทย.
        /// </summary>
        public static string Thai {
            get {
                return ResourceManager.GetString("Thai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลรายการ.
        /// </summary>
        public static string TitleItemInfo {
            get {
                return ResourceManager.GetString("TitleItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลประกอบการดำเนินการ.
        /// </summary>
        public static string TitleOperateData {
            get {
                return ResourceManager.GetString("TitleOperateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งเมลแจ้ง สำนักงาน คปภ..
        /// </summary>
        public static string TitleSendEMail {
            get {
                return ResourceManager.GetString("TitleSendEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อัพโหลด.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload excel file incompleted. Please check excel file..
        /// </summary>
        public static string UPLOAD_ERROR {
            get {
                return ResourceManager.GetString("UPLOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เงื่อนไขการอัปโหลด.
        /// </summary>
        public static string UPLOAD_INSTRUCTION {
            get {
                return ResourceManager.GetString("UPLOAD_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Completed.
        /// </summary>
        public static string UploadCompleted {
            get {
                return ResourceManager.GetString("UploadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลผู้ใช้งาน.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้งาน.
        /// </summary>
        public static string USING {
            get {
                return ResourceManager.GetString("USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้งานข้อมูลสำเร็จ.
        /// </summary>
        public static string UsingCompleted {
            get {
                return ResourceManager.GetString("UsingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช้งานข้อมูลไม่สำเร็จ.
        /// </summary>
        public static string UsingNotComplete {
            get {
                return ResourceManager.GetString("UsingNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string ValComplete {
            get {
                return ResourceManager.GetString("ValComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Data.
        /// </summary>
        public static string ValDisplayData {
            get {
                return ResourceManager.GetString("ValDisplayData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ValError {
            get {
                return ResourceManager.GetString("ValError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string ValFileName {
            get {
                return ResourceManager.GetString("ValFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ผ่านการตรวจสอบข้อมูล.
        /// </summary>
        public static string ValidateError {
            get {
                return ResourceManager.GetString("ValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record All.
        /// </summary>
        public static string ValRecordAll {
            get {
                return ResourceManager.GetString("ValRecordAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิจารณา.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ใช่.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
