//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.Admin.Dashboard", typeof(Dashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่.
        /// </summary>
        public static string ACT_DATE {
            get {
                return ResourceManager.GetString("ACT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to พิจารณาคำร้อง.
        /// </summary>
        public static string CONSIDER_PETITION {
            get {
                return ResourceManager.GetString("CONSIDER_PETITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuer.
        /// </summary>
        public static string ISSUER {
            get {
                return ResourceManager.GetString("ISSUER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการ Certificate.
        /// </summary>
        public static string ManageCertificate {
            get {
                return ResourceManager.GetString("ManageCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กลุ่มบริษัท.
        /// </summary>
        public static string MS_CORP_GROUP {
            get {
                return ResourceManager.GetString("MS_CORP_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริษัท.
        /// </summary>
        public static string MS_CORP_NAME_TH {
            get {
                return ResourceManager.GetString("MS_CORP_NAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ตำแหน่ง.
        /// </summary>
        public static string POSITION {
            get {
                return ResourceManager.GetString("POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ผู้รับผิดชอบ ประพัฒน์ เจ้าหน้าที่ คปภ..
        /// </summary>
        public static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ประเภท.
        /// </summary>
        public static string TODO_TYPE {
            get {
                return ResourceManager.GetString("TODO_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การจัดการบัญชีผู้ใช้งาน.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string USER_FNAME_TH {
            get {
                return ResourceManager.GetString("USER_FNAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อ.
        /// </summary>
        public static string USER_FULLNAME_TH {
            get {
                return ResourceManager.GetString("USER_FULLNAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บัญชีผู้ใช้.
        /// </summary>
        public static string USER_ID {
            get {
                return ResourceManager.GetString("USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to นามสกุล.
        /// </summary>
        public static string USER_LNAME_TH {
            get {
                return ResourceManager.GetString("USER_LNAME_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid From.
        /// </summary>
        public static string VALID_FROM {
            get {
                return ResourceManager.GetString("VALID_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To.
        /// </summary>
        public static string VALID_TO {
            get {
                return ResourceManager.GetString("VALID_TO", resourceCulture);
            }
        }
    }
}
