//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.MIS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISS01P001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISS01P001() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.MIS.MISS01P001", typeof(MISS01P001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Response Time.
        /// </summary>
        public static string ACTUAL_RESTIME {
            get {
                return ResourceManager.GetString("ACTUAL_RESTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Resolution Times (Close).
        /// </summary>
        public static string ACTUAL_RESTIME_CL {
            get {
                return ResourceManager.GetString("ACTUAL_RESTIME_CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Resolution Times (PD).
        /// </summary>
        public static string ACTUAL_RESTIME_PD {
            get {
                return ResourceManager.GetString("ACTUAL_RESTIME_PD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Resolution Times (QA).
        /// </summary>
        public static string ACTUAL_RESTIME_QA {
            get {
                return ResourceManager.GetString("ACTUAL_RESTIME_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Code.
        /// </summary>
        public static string APP_CODE {
            get {
                return ResourceManager.GetString("APP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign user.
        /// </summary>
        public static string ASSIGN {
            get {
                return ResourceManager.GetString("ASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        public static string ASSIGN_USER {
            get {
                return ResourceManager.GetString("ASSIGN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment Calculate.
        /// </summary>
        public static string ASSIGNMENT_CALCULATE {
            get {
                return ResourceManager.GetString("ASSIGNMENT_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Date.
        /// </summary>
        public static string CLOSE_DATE {
            get {
                return ResourceManager.GetString("CLOSE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string COMMENT {
            get {
                return ResourceManager.GetString("COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        public static string DEFECT {
            get {
                return ResourceManager.GetString("DEFECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy PD Date.
        /// </summary>
        public static string DEPLOY_PD {
            get {
                return ResourceManager.GetString("DEPLOY_PD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy QA Date.
        /// </summary>
        public static string DEPLOY_QA {
            get {
                return ResourceManager.GetString("DEPLOY_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DETAIL {
            get {
                return ResourceManager.GetString("DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string EFFECTS {
            get {
                return ResourceManager.GetString("EFFECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESSR No.
        /// </summary>
        public static string ESSR_NO {
            get {
                return ResourceManager.GetString("ESSR_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Id.
        /// </summary>
        public static string FILE_ID {
            get {
                return ResourceManager.GetString("FILE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Packet.
        /// </summary>
        public static string FILEPACKET {
            get {
                return ResourceManager.GetString("FILEPACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Live.
        /// </summary>
        public static string GOLIVE {
            get {
                return ResourceManager.GetString("GOLIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_APP.
        /// </summary>
        public static string ID_APP {
            get {
                return ResourceManager.GetString("ID_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_ISSUE_DATE_PERIOD.
        /// </summary>
        public static string ID_ISSUE_DATE_PERIOD {
            get {
                return ResourceManager.GetString("ID_ISSUE_DATE_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_NO.
        /// </summary>
        public static string ID_NO {
            get {
                return ResourceManager.GetString("ID_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_REF_NO.
        /// </summary>
        public static string ID_REF_NO {
            get {
                return ResourceManager.GetString("ID_REF_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_RESOLUTION_TARGET.
        /// </summary>
        public static string ID_RESOLUTION_TARGET {
            get {
                return ResourceManager.GetString("ID_RESOLUTION_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_RESPONSE_TARGET.
        /// </summary>
        public static string ID_RESPONSE_TARGET {
            get {
                return ResourceManager.GetString("ID_RESPONSE_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Information.
        /// </summary>
        public static string Index1 {
            get {
                return ResourceManager.GetString("Index1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Information.
        /// </summary>
        public static string Index11 {
            get {
                return ResourceManager.GetString("Index11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string Index2 {
            get {
                return ResourceManager.GetString("Index2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string Index21 {
            get {
                return ResourceManager.GetString("Index21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue By.
        /// </summary>
        public static string ISSUE_BY {
            get {
                return ResourceManager.GetString("ISSUE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Calculate.
        /// </summary>
        public static string ISSUE_CALCULATE {
            get {
                return ResourceManager.GetString("ISSUE_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string ISSUE_DATE {
            get {
                return ResourceManager.GetString("ISSUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date Period.
        /// </summary>
        public static string ISSUE_DATE_PERIOD {
            get {
                return ResourceManager.GetString("ISSUE_DATE_PERIOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Datetime.
        /// </summary>
        public static string ISSUE_DATETIME {
            get {
                return ResourceManager.GetString("ISSUE_DATETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Property.
        /// </summary>
        public static string ISSUE_PROPERTY {
            get {
                return ResourceManager.GetString("ISSUE_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Type.
        /// </summary>
        public static string ISSUE_TYPE {
            get {
                return ResourceManager.GetString("ISSUE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBA.
        /// </summary>
        public static string MAN_PLM_DBA {
            get {
                return ResourceManager.GetString("MAN_PLM_DBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL.
        /// </summary>
        public static string MAN_PLM_PL {
            get {
                return ResourceManager.GetString("MAN_PLM_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRG.
        /// </summary>
        public static string MAN_PLM_PRG {
            get {
                return ResourceManager.GetString("MAN_PLM_PRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA.
        /// </summary>
        public static string MAN_PLM_QA {
            get {
                return ResourceManager.GetString("MAN_PLM_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        public static string MAN_PLM_SA {
            get {
                return ResourceManager.GetString("MAN_PLM_SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Menu.
        /// </summary>
        public static string MENU_R {
            get {
                return ResourceManager.GetString("MENU_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name / etc..
        /// </summary>
        public static string MODULE {
            get {
                return ResourceManager.GetString("MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Module Name.
        /// </summary>
        public static string MODULE_R {
            get {
                return ResourceManager.GetString("MODULE_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue No..
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Issue.
        /// </summary>
        public static string OWNER {
            get {
                return ResourceManager.GetString("OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name.
        /// </summary>
        public static string PRG_NAME {
            get {
                return ResourceManager.GetString("PRG_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioriry .
        /// </summary>
        public static string PRIORITY {
            get {
                return ResourceManager.GetString("PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name.
        /// </summary>
        public static string PROGRAM_NAME {
            get {
                return ResourceManager.GetString("PROGRAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Program Name.
        /// </summary>
        public static string PROGRAM_NAME_R {
            get {
                return ResourceManager.GetString("PROGRAM_NAME_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        public static string REF_NO {
            get {
                return ResourceManager.GetString("REF_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No Criteria.
        /// </summary>
        public static string REF_NO_CRITERIA {
            get {
                return ResourceManager.GetString("REF_NO_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        public static string REPORT_TYPR {
            get {
                return ResourceManager.GetString("REPORT_TYPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Target.
        /// </summary>
        public static string RESOLUTION_TARGET {
            get {
                return ResourceManager.GetString("RESOLUTION_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response By.
        /// </summary>
        public static string RESPONSE_BY {
            get {
                return ResourceManager.GetString("RESPONSE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Date.
        /// </summary>
        public static string RESPONSE_DATE {
            get {
                return ResourceManager.GetString("RESPONSE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Target.
        /// </summary>
        public static string RESPONSE_TARGET {
            get {
                return ResourceManager.GetString("RESPONSE_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re Do.
        /// </summary>
        public static string RESTATUS {
            get {
                return ResourceManager.GetString("RESTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Cause.
        /// </summary>
        public static string ROOT_CAUSE {
            get {
                return ResourceManager.GetString("ROOT_CAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVEASSIGN {
            get {
                return ResourceManager.GetString("SAVEASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string SOLUTION {
            get {
                return ResourceManager.GetString("SOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Information.
        /// </summary>
        public static string STEP_1 {
            get {
                return ResourceManager.GetString("STEP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment Issue.
        /// </summary>
        public static string STEP_2 {
            get {
                return ResourceManager.GetString("STEP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Status.
        /// </summary>
        public static string STEP_3 {
            get {
                return ResourceManager.GetString("STEP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status4Golive.
        /// </summary>
        public static string STEP_4 {
            get {
                return ResourceManager.GetString("STEP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status5Close.
        /// </summary>
        public static string STEP_5 {
            get {
                return ResourceManager.GetString("STEP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string TARGET_DATE {
            get {
                return ResourceManager.GetString("TARGET_DATE", resourceCulture);
            }
        }
    }
}
