//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.MIS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISS01P002 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISS01P002() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.MIS.MISS01P002", typeof(MISS01P002).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign user.
        /// </summary>
        public static string ASSIGN {
            get {
                return ResourceManager.GetString("ASSIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Status.
        /// </summary>
        public static string ASSIGN_STATUS {
            get {
                return ResourceManager.GetString("ASSIGN_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        public static string ASSIGN_USER {
            get {
                return ResourceManager.GetString("ASSIGN_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment Calculate.
        /// </summary>
        public static string ASSIGNMENT_CALCULATE {
            get {
                return ResourceManager.GetString("ASSIGNMENT_CALCULATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Complete.
        /// </summary>
        public static string COMPLETE {
            get {
                return ResourceManager.GetString("COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy PD Date.
        /// </summary>
        public static string DEPLOY_PD {
            get {
                return ResourceManager.GetString("DEPLOY_PD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy QA Date.
        /// </summary>
        public static string DEPLOY_QA {
            get {
                return ResourceManager.GetString("DEPLOY_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Packet.
        /// </summary>
        public static string FILE_ID {
            get {
                return ResourceManager.GetString("FILE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Packet.
        /// </summary>
        public static string FILEPACKET {
            get {
                return ResourceManager.GetString("FILEPACKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix by.
        /// </summary>
        public static string FIX_BY {
            get {
                return ResourceManager.GetString("FIX_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Result.
        /// </summary>
        public static string FIXED_RESULT {
            get {
                return ResourceManager.GetString("FIXED_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Live.
        /// </summary>
        public static string GOLIVE {
            get {
                return ResourceManager.GetString("GOLIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_NO.
        /// </summary>
        public static string ID_NO {
            get {
                return ResourceManager.GetString("ID_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID_RESPONSE_BY.
        /// </summary>
        public static string ID_RESPONSE_BY {
            get {
                return ResourceManager.GetString("ID_RESPONSE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Inconplete.
        /// </summary>
        public static string INCOMPLETE {
            get {
                return ResourceManager.GetString("INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment Issue.
        /// </summary>
        public static string INDEX {
            get {
                return ResourceManager.GetString("INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Date.
        /// </summary>
        public static string ISE_DATE_CLOSE {
            get {
                return ResourceManager.GetString("ISE_DATE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow up Date.
        /// </summary>
        public static string ISE_DATE_FOLLOWUP {
            get {
                return ResourceManager.GetString("ISE_DATE_FOLLOWUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Live Date.
        /// </summary>
        public static string ISE_DATE_GOLIVE {
            get {
                return ResourceManager.GetString("ISE_DATE_GOLIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Date.
        /// </summary>
        public static string ISE_DATE_ONPROCESS {
            get {
                return ResourceManager.GetString("ISE_DATE_ONPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string ISE_DATE_OPENING {
            get {
                return ResourceManager.GetString("ISE_DATE_OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Status.
        /// </summary>
        public static string ISE_STATUS {
            get {
                return ResourceManager.GetString("ISE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue By.
        /// </summary>
        public static string ISSUE_BY {
            get {
                return ResourceManager.GetString("ISSUE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string ISSUE_DATE {
            get {
                return ResourceManager.GetString("ISSUE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date From.
        /// </summary>
        public static string ISSUE_DATE_F {
            get {
                return ResourceManager.GetString("ISSUE_DATE_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ISSUE_DATE_T {
            get {
                return ResourceManager.GetString("ISSUE_DATE_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue No..
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Issue.
        /// </summary>
        public static string OWNER {
            get {
                return ResourceManager.GetString("OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReDo.
        /// </summary>
        public static string REDO {
            get {
                return ResourceManager.GetString("REDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        public static string REF_NO {
            get {
                return ResourceManager.GetString("REF_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re Open.
        /// </summary>
        public static string REOPEN {
            get {
                return ResourceManager.GetString("REOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response By.
        /// </summary>
        public static string RESPONSE_BY {
            get {
                return ResourceManager.GetString("RESPONSE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Date.
        /// </summary>
        public static string RESPONSE_DATE {
            get {
                return ResourceManager.GetString("RESPONSE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening.
        /// </summary>
        public static string STEP_1 {
            get {
                return ResourceManager.GetString("STEP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Process.
        /// </summary>
        public static string STEP_2 {
            get {
                return ResourceManager.GetString("STEP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up.
        /// </summary>
        public static string STEP_3 {
            get {
                return ResourceManager.GetString("STEP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go live.
        /// </summary>
        public static string STEP_4 {
            get {
                return ResourceManager.GetString("STEP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string STEP_5 {
            get {
                return ResourceManager.GetString("STEP_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Date.
        /// </summary>
        public static string TARGET_DATE {
            get {
                return ResourceManager.GetString("TARGET_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        public static string TESTING {
            get {
                return ResourceManager.GetString("TESTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        public static string TIMEOUT {
            get {
                return ResourceManager.GetString("TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp PD.
        /// </summary>
        public static string TIMESTEMP_PD {
            get {
                return ResourceManager.GetString("TIMESTEMP_PD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stamp QA.
        /// </summary>
        public static string TIMESTEMP_QA {
            get {
                return ResourceManager.GetString("TIMESTEMP_QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Total.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix By.
        /// </summary>
        public static string USER_ID {
            get {
                return ResourceManager.GetString("USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out of 7 Day.
        /// </summary>
        public static string WAIT_CONFIRM {
            get {
                return ResourceManager.GetString("WAIT_CONFIRM", resourceCulture);
            }
        }
    }
}
