//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.MIS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISS01P003 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISS01P003() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.MIS.MISS01P003", typeof(MISS01P003).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string ACCEPT {
            get {
                return ResourceManager.GetString("ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept | Reject.
        /// </summary>
        public static string ACCEPT_REJECT {
            get {
                return ResourceManager.GetString("ACCEPT_REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreed.
        /// </summary>
        public static string AGREED {
            get {
                return ResourceManager.GetString("AGREED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Done.
        /// </summary>
        public static string CONFIRM_FIXED {
            get {
                return ResourceManager.GetString("CONFIRM_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string ISE_DATE_OPENING {
            get {
                return ResourceManager.GetString("ISE_DATE_OPENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue No.
        /// </summary>
        public static string ISE_NO {
            get {
                return ResourceManager.GetString("ISE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string REJECT {
            get {
                return ResourceManager.GetString("REJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response By.
        /// </summary>
        public static string RESPONSE_BY {
            get {
                return ResourceManager.GetString("RESPONSE_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Result.
        /// </summary>
        public static string SOLUTION_TEXT {
            get {
                return ResourceManager.GetString("SOLUTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewTask.
        /// </summary>
        public static string STEP_1 {
            get {
                return ResourceManager.GetString("STEP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoTask.
        /// </summary>
        public static string STEP_2 {
            get {
                return ResourceManager.GetString("STEP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoneTask.
        /// </summary>
        public static string STEP_3 {
            get {
                return ResourceManager.GetString("STEP_3", resourceCulture);
            }
        }
    }
}
