//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation.MIS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISS02P001 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISS02P001() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Translation.MIS.MISS02P001", typeof(MISS02P001).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment (day).
        /// </summary>
        public static string ALL_DEPLOYMENT_DATE {
            get {
                return ResourceManager.GetString("ALL_DEPLOYMENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment PO (day).
        /// </summary>
        public static string ALL_DEPLOYMENT_IT {
            get {
                return ResourceManager.GetString("ALL_DEPLOYMENT_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday (day).
        /// </summary>
        public static string ALL_HOLIDAY {
            get {
                return ResourceManager.GetString("ALL_HOLIDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday Working (day).
        /// </summary>
        public static string ALL_SATURDAY_W {
            get {
                return ResourceManager.GetString("ALL_SATURDAY_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Program Package (day).
        /// </summary>
        public static string ALL_SPP {
            get {
                return ResourceManager.GetString("ALL_SPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Infomation.
        /// </summary>
        public static string DATE_INFO {
            get {
                return ResourceManager.GetString("DATE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DAY {
            get {
                return ResourceManager.GetString("DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy Program.
        /// </summary>
        public static string DEPLOY_PRG {
            get {
                return ResourceManager.GetString("DEPLOY_PRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deplot For User.
        /// </summary>
        public static string DEPLOY_USER {
            get {
                return ResourceManager.GetString("DEPLOY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V-Smart infrom issue no deployment on next Monday.
        /// </summary>
        public static string DEPLOYMENT_DATE {
            get {
                return ResourceManager.GetString("DEPLOYMENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string FLAG {
            get {
                return ResourceManager.GetString("FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string REMARK {
            get {
                return ResourceManager.GetString("REMARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Day.
        /// </summary>
        public static string TYPE_DAY {
            get {
                return ResourceManager.GetString("TYPE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Instruction.
        /// </summary>
        public static string UPLOAD_INSTRUCTION {
            get {
                return ResourceManager.GetString("UPLOAD_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
    }
}
